### ISSUE TITLE
Crush on Start up

### ISSUE THREAD

**Issue by aalsabi** [kokoko3k/xt7-player-mpv#4] opened 2015-09-05 23:57 UTC
xt7-player-mpv-master: 0.9.2371

System.fullversion: 3.8.90

System.Architecture: x86_64

mpv: 
mpv git-d04d238 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on Fri Sep  4 16:31:50 UTC 2015
ffmpeg library versions:
   libavutil       54.31.100
   libavcodec      56.60.100
   libavformat     56.40.101
   libswscale      3.1.101
   libavfilter     5.40.101
   libswresample   1.2.101
ffmpeg version: N-74831-ga51d424

**Comment by kokoko3k** [comment] 2015-09-06 18:05
Closed because duplicate of https://github.com/kokoko3k/xt7-player-mpv/issues/5

**Closed as completed by kokoko3k** 2015-09-06 18:05 UTC
